import { SignIn } from "@clerk/nextjs";

export const metadata = {
  title: "Register - My Pop Off",
  description: "Generated by create next app",
};

export default function Register() {
  return (
    <section className="flex items-center justify-center h-screen min-h-fit">
      <SignIn />
    </section>
  );
}
