import "../(public)/globals.scss";
import Link from "next/link";
import { AiOutlineDashboard } from "react-icons/ai";
import { CgLogOff, CgPerformance, CgUser, CgWebsite } from "react-icons/cg";
import { ImCog } from "react-icons/im";
import { RiPaletteLine } from "react-icons/ri";
import DarkModeToggle from "@/components/DarkModeToggle";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/oya4ufz.css" />
      </head>
      <body className="p-6 flex flex-row items-stretch w-full h-screen min-h-fit bg-primary-light dark:bg-primary-dark">
        <nav className="pb-6 flex flex-col justify-between w-1/6 text-primary-dark dark:text-primary-light font-light font-base">
          <section className="flex flex-col">
            <p className="pb-12 text-lg text-action dark:text-action font-bold font-display">
              <Link href="/">My Pop Off</Link>
            </p>
            <ul className="flex flex-col gap-8">
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <CgPerformance size={20} /> Dashboard
              </li>
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <CgWebsite size={20} /> Landing Page
              </li>
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <RiPaletteLine size={20} /> Customise
              </li>
            </ul>
          </section>
          <section>
            <ul className="flex flex-col gap-8">
              <DarkModeToggle />
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <CgUser size={20} />
                Account
              </li>
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <ImCog size={18} /> Settings
              </li>
              <li className="flex gap-3 items-center hover:text-action transition-all duration-300">
                <CgLogOff size={20} /> Logout
              </li>
            </ul>
          </section>
        </nav>

        <main className="w-full h-full bg-dashboard-primary-light dark:bg-dashboard-primary-dark rounded-3xl shadow-xl shadow-black/40 overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
